# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 476cbdfc2a5af3839da6cb9ecd17186a371268e820dc09374c997b52c6e70e3a00c4a3798661257f218c52c56f6b6c357ea666c7784f5bfe9c9cf5a528b5c360

test:
  secret_key_base: 625d355d53d724d12566fc7b95d23785ddea4ba4a3f8251fa76bb40d72d2121615ce3d5a2f3713cff9e15a80891ca101401c857b76c6d1b8bf8e0929c7db07a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
